# Generated by Django 4.1.3 on 2023-07-15 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bairro",
            fields=[
                (
                    "id",
                    models.AutoField(
                        db_column="id_bairro", primary_key=True, serialize=False
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        db_column="nome_bairro",
                        max_length=100,
                        verbose_name="Nome do Bairro",
                    ),
                ),
            ],
            options={
                "db_table": "bairro",
            },
        ),
        migrations.CreateModel(
            name="Municipe",
            fields=[
                (
                    "id",
                    models.AutoField(
                        db_column="id_municipe", primary_key=True, serialize=False
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        db_column="nome_municipe", max_length=100, verbose_name="Nome"
                    ),
                ),
                (
                    "data_nascimento",
                    models.DateField(
                        db_column="data_nascimento", verbose_name="Data de Nascimento"
                    ),
                ),
                ("genero", models.CharField(db_column="genero", max_length=20)),
                ("nuit", models.CharField(db_column="nuit", max_length=20)),
                (
                    "bilhete_identidade",
                    models.CharField(
                        db_column="bilhete_identidade",
                        max_length=20,
                        verbose_name="Bilhete de Identidade",
                    ),
                ),
                ("telefone", models.CharField(db_column="telefone", max_length=20)),
                ("email", models.EmailField(db_column="email", max_length=100)),
                (
                    "tipo_municipe",
                    models.CharField(
                        db_column="tipo_municipe",
                        max_length=100,
                        verbose_name="Tipo de Municipe",
                    ),
                ),
                (
                    "nr_contribuente",
                    models.CharField(
                        db_column="nr_contribuente",
                        max_length=20,
                        verbose_name="Número de Contribuinte",
                    ),
                ),
                (
                    "data_registro",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_column="data_registro",
                        verbose_name="Data de Registro",
                    ),
                ),
                (
                    "bairro",
                    models.ForeignKey(
                        db_column="bairro_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Municipe.bairro",
                        verbose_name="Bairro",
                    ),
                ),
            ],
            options={
                "db_table": "municipe",
            },
        ),
    ]
