# Generated by Django 4.1.3 on 2023-07-15 16:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("Municipe", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="municipe",
            name="user",
            field=models.OneToOneField(
                db_column="utilizador",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
