# Generated by Django 4.1.3 on 2023-07-15 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Municipe", "0002_municipe_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="municipe",
            name="nr_contribuente",
            field=models.CharField(
                db_column="nr_contribuente",
                max_length=20,
                null=True,
                verbose_name="Número de Contribuinte",
            ),
        ),
    ]
