# Generated by Django 4.1.3 on 2023-07-25 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Municipe", "0003_alter_municipe_nr_contribuente"),
    ]

    operations = [
        migrations.AddField(
            model_name="municipe",
            name="nacionalidade",
            field=models.CharField(
                db_column="nacionalidade", default="Moçambicano(a)", max_length=50
            ),
        ),
    ]
