# Generated by Django 4.2.4 on 2023-09-17 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Municipe', '0006_alter_municipe_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='municipe',
            name='email',
            field=models.CharField(db_column='email', max_length=100, null=True),
        ),
    ]
