# Generated by Django 4.1.3 on 2023-07-30 03:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("pagamentos", "0009_transpagamento"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LicensaDuat",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nome", models.CharField(max_length=100)),
                ("data_nasc", models.CharField(max_length=100, null=True)),
                ("naturalidade", models.CharField(max_length=100)),
                ("bi", models.CharField(max_length=100, null=True)),
                ("bi_emissao", models.CharField(max_length=100)),
                ("bi_local", models.CharField(max_length=100)),
                (
                    "status",
                    models.CharField(default="Aguardando Aprovacao", max_length=100),
                ),
                ("data_registo", models.DateTimeField(auto_now_add=True, null=True)),
                ("data_aprovacao", models.DateTimeField(null=True)),
                (
                    "bairro",
                    models.CharField(default="Nhocane", max_length=100, null=True),
                ),
                ("quateirao", models.CharField(max_length=100, null=True)),
                ("area", models.CharField(max_length=100, null=True)),
                ("data_atribuicao", models.CharField(max_length=100, null=True)),
                (
                    "pagamento",
                    models.OneToOneField(
                        db_column="id_pagamento_urbanizacao",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pagamentos.urbpagamento",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user_id",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
