# Generated by Django 4.1.3 on 2023-07-30 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("urbanizacao", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="licensaduat",
            old_name="quateirao",
            new_name="quarteirao",
        ),
    ]
