# Generated by Django 4.1.3 on 2023-07-31 11:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("pagamentos", "0009_transpagamento"),
        ("urbanizacao", "0002_rename_quateirao_licensaduat_quarteirao"),
    ]

    operations = [
        migrations.AlterField(
            model_name="licensaduat",
            name="bairro",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.CreateModel(
            name="LicensaConstrucao",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nome", models.CharField(max_length=100)),
                ("data_nasc", models.CharField(max_length=100, null=True)),
                ("naturalidade", models.CharField(max_length=100)),
                ("bi", models.CharField(max_length=100, null=True)),
                ("bi_emissao", models.CharField(max_length=100)),
                ("bi_local", models.CharField(max_length=100)),
                (
                    "status",
                    models.CharField(default="Aguardando Aprovacao", max_length=100),
                ),
                ("data_registo", models.DateTimeField(auto_now_add=True, null=True)),
                ("data_aprovacao", models.DateTimeField(null=True)),
                ("bairro", models.CharField(max_length=100, null=True)),
                ("quarteirao", models.CharField(max_length=100, null=True)),
                ("finalidade", models.CharField(max_length=100)),
                ("area_lougradouro", models.CharField(max_length=100)),
                ("area_construcao", models.CharField(max_length=100)),
                ("nr_pisos", models.IntegerField()),
                ("destino_obra", models.CharField(max_length=100)),
                ("valor_obra", models.DecimalField(decimal_places=2, max_digits=10)),
                ("regime_obra", models.CharField(max_length=100)),
                ("responsavel_obra", models.CharField(max_length=100)),
                ("responsavel_nr", models.CharField(max_length=100)),
                (
                    "pagamento",
                    models.OneToOneField(
                        db_column="id_pagamento_urbanizacao",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pagamentos.urbpagamento",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user_id",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
