# Generated by Django 4.1.3 on 2023-07-15 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Municipe", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Automovel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        db_column="id_automovel", primary_key=True, serialize=False
                    ),
                ),
                (
                    "matricula",
                    models.CharField(
                        db_column="matricula", max_length=20, verbose_name="Matrícula"
                    ),
                ),
                ("marca", models.CharField(db_column="marca", max_length=100)),
                ("modelo", models.CharField(db_column="modelo", max_length=100)),
                (
                    "combustivel",
                    models.CharField(db_column="combustivel", max_length=50),
                ),
                ("cilindrada", models.CharField(db_column="cilindrada", max_length=50)),
                ("lotacao", models.CharField(db_column="lotacao", max_length=50)),
                (
                    "ano_fabrico",
                    models.IntegerField(
                        db_column="ano_fabrico", verbose_name="Ano de Fabrico"
                    ),
                ),
                (
                    "ano_compra",
                    models.IntegerField(
                        db_column="ano_compra", verbose_name="Ano de Compra"
                    ),
                ),
                ("tipo", models.CharField(db_column="tipo", max_length=50)),
                ("natureza", models.CharField(db_column="natureza", max_length=50)),
                (
                    "nr_contribuente",
                    models.CharField(
                        db_column="nr_contribuente",
                        max_length=20,
                        verbose_name="Número de Contribuinte",
                    ),
                ),
                ("capacidade", models.CharField(db_column="capacidade", max_length=50)),
                (
                    "capacidade_carga",
                    models.CharField(db_column="capacidade_carga", max_length=50),
                ),
                (
                    "id_municipe",
                    models.ForeignKey(
                        db_column="id_Municipe",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Municipe.municipe",
                    ),
                ),
            ],
            options={
                "db_table": "automovel",
            },
        ),
    ]
