# Generated by Django 4.1.3 on 2023-07-15 16:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("automovel", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="automovel",
            name="data_registro",
            field=models.DateTimeField(
                auto_now_add=True,
                db_column="data_registro",
                default=django.utils.timezone.now,
                verbose_name="Data de Registro",
            ),
            preserve_default=False,
        ),
    ]
