# Generated by Django 4.1.3 on 2023-07-15 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Municipe", "0003_alter_municipe_nr_contribuente"),
        ("automovel", "0002_automovel_data_registro"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="automovel",
            name="capacidade",
        ),
        migrations.AlterField(
            model_name="automovel",
            name="id_municipe",
            field=models.ForeignKey(
                db_column="id_Municipe",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Municipe.municipe",
            ),
        ),
    ]
