# Generated by Django 4.1.3 on 2023-07-15 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("automovel", "0003_remove_automovel_capacidade_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="automovel",
            name="nr_contribuente",
        ),
    ]
