# Generated by Django 4.1.3 on 2023-07-17 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("automovel", "0004_remove_automovel_nr_contribuente"),
    ]

    operations = [
        migrations.CreateModel(
            name="Automovel_Grupo",
            fields=[
                ("idGrupo", models.BigAutoField(primary_key=True, serialize=False)),
                ("grupo", models.CharField(default="ola", max_length=50)),
                ("cilindara_inicialg", models.CharField(default="ola", max_length=50)),
                ("cilindara_finalg", models.CharField(default="ola", max_length=50)),
                ("cilindara_inicialdi", models.CharField(default="ola", max_length=50)),
                ("cilindara_finaldi", models.CharField(default="ola", max_length=50)),
                (
                    "cilindara_inicialvol",
                    models.CharField(default="ola", max_length=50),
                ),
                ("cilindara_finaldvol", models.CharField(default="ola", max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Automovel_Grupo_Escalao",
            fields=[
                ("idEscalao", models.BigAutoField(primary_key=True, serialize=False)),
                ("primeiro_escalao", models.CharField(default="ola", max_length=50)),
                ("segundo_escalao", models.CharField(default="ola", max_length=50)),
                ("Terceiro_escalao", models.CharField(default="ola", max_length=50)),
                (
                    "grupo",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="automovel.automovel_grupo",
                    ),
                ),
            ],
        ),
    ]
