# Generated by Django 4.1.3 on 2023-07-16 15:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("Municipe", "0003_alter_municipe_nr_contribuente"),
        ("impostos", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pagamento",
            fields=[
                (
                    "id",
                    models.AutoField(
                        db_column="id_pagamento", primary_key=True, serialize=False
                    ),
                ),
                (
                    "valor",
                    models.DecimalField(
                        db_column="valor", decimal_places=2, max_digits=10
                    ),
                ),
                ("data", models.DateTimeField(auto_now_add=True, db_column="data")),
                (
                    "bairro",
                    models.ForeignKey(
                        db_column="bairro_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Municipe.bairro",
                        verbose_name="Bairro",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "pagamento",
            },
        ),
        migrations.CreateModel(
            name="IpaPagamento",
            fields=[
                (
                    "id",
                    models.AutoField(
                        db_column="id_ipa_pagamento", primary_key=True, serialize=False
                    ),
                ),
                ("epoca", models.CharField(db_column="epoca", max_length=100)),
                (
                    "imposto",
                    models.ForeignKey(
                        db_column="id_imposto",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="impostos.imposto",
                    ),
                ),
                (
                    "municipe",
                    models.ForeignKey(
                        db_column="id_municipe",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ipa_pagamentos",
                        to="Municipe.municipe",
                    ),
                ),
                (
                    "pagamento",
                    models.ForeignKey(
                        db_column="id_pagamento",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pagamentos.pagamento",
                    ),
                ),
            ],
            options={
                "db_table": "ipa_pagamento",
            },
        ),
    ]
