# Generated by Django 4.1.3 on 2023-07-17 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Municipe", "0003_alter_municipe_nr_contribuente"),
        ("impostos", "0001_initial"),
        ("Propriedade", "0004_alter_propriedade_bairro"),
        ("pagamentos", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PropPagamento",
            fields=[
                (
                    "id",
                    models.AutoField(
                        db_column="id_prop_pagamento", primary_key=True, serialize=False
                    ),
                ),
                ("epoca", models.CharField(db_column="epoca", max_length=100)),
                (
                    "imposto",
                    models.ForeignKey(
                        db_column="id_imposto",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="impostos.imposto",
                    ),
                ),
                (
                    "municipe",
                    models.ForeignKey(
                        db_column="id_municipe",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Municipe.municipe",
                    ),
                ),
                (
                    "pagamento",
                    models.ForeignKey(
                        db_column="id_pagamento",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pagamentos.pagamento",
                    ),
                ),
                (
                    "propriedade",
                    models.ForeignKey(
                        db_column="id_propriedade",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Propriedade.propriedade",
                    ),
                ),
            ],
            options={
                "db_table": "prop_pagamento",
            },
        ),
    ]
