# Generated by Django 4.1.3 on 2023-07-17 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("automovel", "0005_automovel_grupo_automovel_grupo_escalao"),
        ("impostos", "0001_initial"),
        ("Municipe", "0003_alter_municipe_nr_contribuente"),
        ("pagamentos", "0002_proppagamento"),
    ]

    operations = [
        migrations.CreateModel(
            name="IavPagamento",
            fields=[
                (
                    "id",
                    models.AutoField(
                        db_column="id_iav_pagamento", primary_key=True, serialize=False
                    ),
                ),
                ("epoca", models.CharField(db_column="epoca", max_length=100)),
                (
                    "automovel",
                    models.ForeignKey(
                        db_column="id_automovel",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="automovel.automovel",
                    ),
                ),
                (
                    "imposto",
                    models.ForeignKey(
                        db_column="id_imposto",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="impostos.imposto",
                    ),
                ),
                (
                    "municipe",
                    models.ForeignKey(
                        db_column="id_municipe",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Municipe.municipe",
                    ),
                ),
                (
                    "pagamento",
                    models.ForeignKey(
                        db_column="id_pagamento",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pagamentos.pagamento",
                    ),
                ),
            ],
            options={
                "db_table": "iav_pagamento",
            },
        ),
    ]
