# Generated by Django 4.1.3 on 2023-07-18 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Municipe", "0003_alter_municipe_nr_contribuente"),
        ("taxas", "0001_initial"),
        ("estabelecimento", "0001_initial"),
        ("pagamentos", "0003_iavpagamento"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaePagamento",
            fields=[
                (
                    "id",
                    models.AutoField(
                        db_column="id_tae_pagamento", primary_key=True, serialize=False
                    ),
                ),
                ("epoca", models.CharField(db_column="epoca", max_length=100)),
                (
                    "estabelecimento",
                    models.ForeignKey(
                        db_column="id_estabelecimento",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="estabelecimento.estabelecimento",
                    ),
                ),
                (
                    "municipe",
                    models.ForeignKey(
                        db_column="id_municipe",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Municipe.municipe",
                    ),
                ),
                (
                    "pagamento",
                    models.ForeignKey(
                        db_column="id_pagamento",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pagamentos.pagamento",
                    ),
                ),
                (
                    "taxa",
                    models.ForeignKey(
                        db_column="id_taxa",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="taxas.taxa",
                    ),
                ),
            ],
            options={
                "db_table": "tae_pagamento",
            },
        ),
    ]
