# Generated by Django 4.1.3 on 2023-07-19 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("taxas", "0001_initial"),
        ("Municipe", "0003_alter_municipe_nr_contribuente"),
        ("pagamentos", "0004_taepagamento"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeclaracaoPagamento",
            fields=[
                (
                    "id",
                    models.AutoField(
                        db_column="id_declaracao_pagamento",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "municipe",
                    models.ForeignKey(
                        db_column="id_municipe",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Municipe.municipe",
                    ),
                ),
                (
                    "pagamento",
                    models.ForeignKey(
                        db_column="id_pagamento",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pagamentos.pagamento",
                    ),
                ),
                (
                    "taxa",
                    models.ForeignKey(
                        db_column="id_taxa",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="taxas.taxa",
                    ),
                ),
            ],
            options={
                "db_table": "declaracao_pagamento",
            },
        ),
    ]
