# Generated by Django 4.1.3 on 2023-07-25 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Propriedade", "0004_alter_propriedade_bairro"),
        ("Municipe", "0004_municipe_nacionalidade"),
        ("taxas", "0002_alter_taxa_nome"),
        ("pagamentos", "0005_declaracaopagamento"),
    ]

    operations = [
        migrations.CreateModel(
            name="UrbPagamento",
            fields=[
                (
                    "id",
                    models.AutoField(
                        db_column="id_urb_pagamento", primary_key=True, serialize=False
                    ),
                ),
                (
                    "municipe",
                    models.ForeignKey(
                        db_column="id_municipe",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Municipe.municipe",
                    ),
                ),
                (
                    "pagamento",
                    models.ForeignKey(
                        db_column="id_pagamento",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pagamentos.pagamento",
                    ),
                ),
                (
                    "propriedade",
                    models.ForeignKey(
                        db_column="id_propriedade",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Propriedade.propriedade",
                    ),
                ),
                (
                    "taxa",
                    models.ForeignKey(
                        db_column="id_taxa",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="taxas.taxa",
                    ),
                ),
            ],
            options={
                "db_table": "urbanizacao_pagamento",
            },
        ),
    ]
