# Generated by Django 4.1.3 on 2023-07-26 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pagamentos", "0006_urbpagamento"),
    ]

    operations = [
        migrations.AddField(
            model_name="pagamento",
            name="metodo",
            field=models.CharField(
                db_column="metodo", default="Numerário", max_length=100, null=True
            ),
        ),
    ]
