# Generated by Django 4.1.3 on 2023-08-07 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("taxas", "0002_alter_taxa_nome"),
        ("Municipe", "0005_mercado"),
        ("pagamentos", "0010_residualpagamento"),
    ]

    operations = [
        migrations.CreateModel(
            name="MercadoPagamento",
            fields=[
                (
                    "id",
                    models.AutoField(
                        db_column="id_mercado_pagamento",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "mercado",
                    models.ForeignKey(
                        db_column="id_mercado",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Municipe.mercado",
                    ),
                ),
                (
                    "municipe",
                    models.ForeignKey(
                        db_column="id_municipe",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Municipe.municipe",
                    ),
                ),
                (
                    "pagamento",
                    models.ForeignKey(
                        db_column="id_pagamento",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pagamentos.pagamento",
                    ),
                ),
                (
                    "taxa",
                    models.ForeignKey(
                        db_column="id_taxa",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="taxas.taxa",
                    ),
                ),
            ],
            options={
                "db_table": "mercado_pagamento",
            },
        ),
    ]
