# Generated by Django 4.2.4 on 2023-09-04 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagamentos', '0013_pagamento_ispaid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagamento',
            name='isPaid',
            field=models.BooleanField(db_column='status', default=False),
        ),
    ]
