# Generated by Django 4.1.3 on 2023-08-02 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audiencia", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="audiencia",
            name="data_registo",
            field=models.DateField(auto_now=True, db_column="data_registo"),
        ),
    ]
