# Generated by Django 4.2.4 on 2023-09-19 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audiencia', '0003_alter_audiencia_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiencia',
            name='pedido',
            field=models.FileField(null=True, upload_to='pedidos/'),
        ),
        migrations.AlterField(
            model_name='audiencia',
            name='data',
            field=models.DateField(db_column='data', null=True),
        ),
        migrations.AlterField(
            model_name='audiencia',
            name='data_registo',
            field=models.DateField(auto_now=True, db_column='data_registo', null=True),
        ),
        migrations.AlterField(
            model_name='audiencia',
            name='descricao',
            field=models.CharField(db_column='descricao', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='audiencia',
            name='estado',
            field=models.CharField(db_column='estado', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='audiencia',
            name='hora',
            field=models.TimeField(db_column='hora', null=True),
        ),
        migrations.AlterField(
            model_name='audiencia',
            name='local',
            field=models.CharField(db_column='local', max_length=100, null=True),
        ),
    ]
