# Generated by Django 4.1.3 on 2023-08-01 12:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("Municipe", "0004_municipe_nacionalidade"),
    ]

    operations = [
        migrations.CreateModel(
            name="Unidade",
            fields=[
                (
                    "id",
                    models.AutoField(
                        db_column="id_unidade", primary_key=True, serialize=False
                    ),
                ),
                ("nome", models.CharField(db_column="nome", max_length=100)),
            ],
            options={
                "db_table": "unidade",
            },
        ),
        migrations.CreateModel(
            name="Funcionario",
            fields=[
                (
                    "id",
                    models.AutoField(
                        db_column="id_funcionario", primary_key=True, serialize=False
                    ),
                ),
                ("cargo", models.CharField(db_column="cargo", max_length=100)),
                (
                    "municipe",
                    models.ForeignKey(
                        db_column="id_municipe",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Municipe.municipe",
                    ),
                ),
                (
                    "unidade",
                    models.ForeignKey(
                        db_column="id_unidade",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="administracao.unidade",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        db_column="utilizador",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "funcionario",
            },
        ),
    ]
