# Generated by Django 4.1.3 on 2023-08-01 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administracao", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="funcionario",
            name="isActive",
            field=models.BooleanField(db_column="isActive", default=True),
        ),
    ]
