# Generated by Django 4.2.4 on 2023-08-15 21:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('automovel', '0005_automovel_grupo_automovel_grupo_escalao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pagamentos', '0012_genericopagamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='LicensaTransporte',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rota', models.CharField(max_length=100, null=True)),
                ('status', models.CharField(default='Aguardando Aprovacao', max_length=100)),
                ('data_registo', models.DateTimeField(auto_now_add=True, null=True)),
                ('data_aprovacao', models.DateTimeField(null=True)),
                ('pagamento', models.OneToOneField(db_column='id_pagamento_transporte', on_delete=django.db.models.deletion.CASCADE, to='pagamentos.transpagamento')),
                ('user', models.ForeignKey(db_column='user_id', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('veiculo', models.ForeignKey(db_column='id_automovel', null=True, on_delete=django.db.models.deletion.CASCADE, to='automovel.automovel')),
            ],
        ),
        migrations.CreateModel(
            name='LicensaAgua',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(default='Aguardando Aprovacao', max_length=100)),
                ('data_registo', models.DateTimeField(auto_now_add=True, null=True)),
                ('data_aprovacao', models.DateTimeField(null=True)),
                ('pagamento', models.OneToOneField(db_column='id_pagamento_transporte', on_delete=django.db.models.deletion.CASCADE, to='pagamentos.transpagamento')),
                ('user', models.ForeignKey(db_column='user_id', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
