# Generated by Django 4.2.4 on 2023-08-16 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planificacao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='licensaagua',
            name='bairro',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='licensaagua',
            name='nr_casa',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='licensaagua',
            name='quarteirao',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
