# Generated by Django 4.2.4 on 2023-09-19 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planificacao', '0002_licensaagua_bairro_licensaagua_nr_casa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='licensaagua',
            name='pedido',
            field=models.FileField(null=True, upload_to='pedidos/'),
        ),
        migrations.AddField(
            model_name='licensatransporte',
            name='pedido',
            field=models.FileField(null=True, upload_to='pedidos/'),
        ),
    ]
