# Generated by Django 4.1.3 on 2023-07-19 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("pagamentos", "0005_declaracaopagamento"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeclaracaoViagem",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nome", models.CharField(max_length=100)),
                ("idade", models.PositiveIntegerField()),
                ("pai", models.CharField(max_length=100)),
                ("mae", models.CharField(max_length=100)),
                ("naturalidade", models.CharField(max_length=100)),
                ("bi_emissao", models.DateField()),
                ("bi_local", models.CharField(max_length=100)),
                ("nome_menor", models.CharField(max_length=100)),
                ("relacao_menor", models.CharField(max_length=100)),
                ("razao", models.CharField(max_length=100)),
                ("tempo_residencia", models.CharField(max_length=100)),
                (
                    "pagamento",
                    models.ForeignKey(
                        db_column="id_pagamento_declaracao",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pagamentos.declaracaopagamento",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DeclaracaoResidencia",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nome", models.CharField(max_length=100)),
                ("idade", models.PositiveIntegerField()),
                ("pai", models.CharField(max_length=100)),
                ("mae", models.CharField(max_length=100)),
                ("naturalidade", models.CharField(max_length=100)),
                ("bi_emissao", models.DateField()),
                ("bi_local", models.CharField(max_length=100)),
                ("razao", models.CharField(max_length=100)),
                ("tempo_residencia", models.CharField(max_length=100)),
                (
                    "pagamento",
                    models.ForeignKey(
                        db_column="id_pagamento_declaracao",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pagamentos.declaracaopagamento",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DeclaracaoPobreza",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nome", models.CharField(max_length=100)),
                ("idade", models.PositiveIntegerField()),
                ("pai", models.CharField(max_length=100)),
                ("mae", models.CharField(max_length=100)),
                ("naturalidade", models.CharField(max_length=100)),
                ("bi_emissao", models.DateField()),
                ("bi_local", models.CharField(max_length=100)),
                ("razao", models.CharField(max_length=100)),
                ("tempo_residencia", models.CharField(max_length=100)),
                (
                    "pagamento",
                    models.ForeignKey(
                        db_column="id_pagamento_declaracao",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pagamentos.declaracaopagamento",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DeclaracaoObito",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nome", models.CharField(max_length=100)),
                ("idade", models.PositiveIntegerField()),
                ("pai", models.CharField(max_length=100)),
                ("mae", models.CharField(max_length=100)),
                ("naturalidade", models.CharField(max_length=100)),
                ("bi_emissao", models.DateField()),
                ("bi_local", models.CharField(max_length=100)),
                ("data_obito", models.DateField()),
                ("razao_obito", models.CharField(max_length=100)),
                (
                    "pagamento",
                    models.ForeignKey(
                        db_column="id_pagamento_declaracao",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pagamentos.declaracaopagamento",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DeclaracaoMatricial",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nome", models.CharField(max_length=100)),
                ("idade", models.PositiveIntegerField()),
                ("pai", models.CharField(max_length=100)),
                ("mae", models.CharField(max_length=100)),
                ("naturalidade", models.CharField(max_length=100)),
                ("bi_emissao", models.DateField()),
                ("bi_local", models.CharField(max_length=100)),
                (
                    "pagamento",
                    models.ForeignKey(
                        db_column="id_pagamento_declaracao",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pagamentos.declaracaopagamento",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DeclaracaoCredencialViagem",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nome", models.CharField(max_length=100)),
                ("idade", models.PositiveIntegerField()),
                ("pai", models.CharField(max_length=100)),
                ("mae", models.CharField(max_length=100)),
                ("naturalidade", models.CharField(max_length=100)),
                ("bi_emissao", models.DateField()),
                ("bi_local", models.CharField(max_length=100)),
                ("veiculo_marca", models.CharField(max_length=100)),
                ("veiculo_matricula", models.CharField(max_length=100)),
                ("lotacao", models.PositiveIntegerField()),
                ("validade", models.DateField()),
                (
                    "pagamento",
                    models.ForeignKey(
                        db_column="id_pagamento_declaracao",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pagamentos.declaracaopagamento",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DeclaracaoCoabitacao",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nome", models.CharField(max_length=100)),
                ("idade", models.PositiveIntegerField()),
                ("pai", models.CharField(max_length=100)),
                ("mae", models.CharField(max_length=100)),
                ("naturalidade", models.CharField(max_length=100)),
                ("bi_emissao", models.DateField()),
                ("bi_local", models.CharField(max_length=100)),
                ("conjo", models.CharField(max_length=100)),
                ("tempo_residencia", models.CharField(max_length=100)),
                (
                    "pagamento",
                    models.ForeignKey(
                        db_column="id_pagamento_declaracao",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pagamentos.declaracaopagamento",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
