# Generated by Django 4.1.3 on 2023-07-19 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("pagamentos", "0005_declaracaopagamento"),
        ("declaracao", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="declaracaocoabitacao",
            name="pagamento",
            field=models.OneToOneField(
                db_column="id_pagamento_declaracao",
                on_delete=django.db.models.deletion.CASCADE,
                to="pagamentos.declaracaopagamento",
            ),
        ),
        migrations.AlterField(
            model_name="declaracaocredencialviagem",
            name="pagamento",
            field=models.OneToOneField(
                db_column="id_pagamento_declaracao",
                on_delete=django.db.models.deletion.CASCADE,
                to="pagamentos.declaracaopagamento",
            ),
        ),
        migrations.AlterField(
            model_name="declaracaomatricial",
            name="pagamento",
            field=models.OneToOneField(
                db_column="id_pagamento_declaracao",
                on_delete=django.db.models.deletion.CASCADE,
                to="pagamentos.declaracaopagamento",
            ),
        ),
        migrations.AlterField(
            model_name="declaracaoobito",
            name="pagamento",
            field=models.OneToOneField(
                db_column="id_pagamento_declaracao",
                on_delete=django.db.models.deletion.CASCADE,
                to="pagamentos.declaracaopagamento",
            ),
        ),
        migrations.AlterField(
            model_name="declaracaopobreza",
            name="pagamento",
            field=models.OneToOneField(
                db_column="id_pagamento_declaracao",
                on_delete=django.db.models.deletion.CASCADE,
                to="pagamentos.declaracaopagamento",
            ),
        ),
        migrations.AlterField(
            model_name="declaracaoresidencia",
            name="pagamento",
            field=models.OneToOneField(
                db_column="id_pagamento_declaracao",
                on_delete=django.db.models.deletion.CASCADE,
                to="pagamentos.declaracaopagamento",
            ),
        ),
        migrations.AlterField(
            model_name="declaracaoviagem",
            name="pagamento",
            field=models.OneToOneField(
                db_column="id_pagamento_declaracao",
                on_delete=django.db.models.deletion.CASCADE,
                to="pagamentos.declaracaopagamento",
            ),
        ),
    ]
