# Generated by Django 4.1.3 on 2023-07-20 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("declaracao", "0003_alter_declaracaocoabitacao_bi_emissao_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="declaracaocoabitacao",
            name="idade",
        ),
        migrations.RemoveField(
            model_name="declaracaocredencialviagem",
            name="idade",
        ),
        migrations.RemoveField(
            model_name="declaracaomatricial",
            name="idade",
        ),
        migrations.RemoveField(
            model_name="declaracaoobito",
            name="idade",
        ),
        migrations.RemoveField(
            model_name="declaracaopobreza",
            name="idade",
        ),
        migrations.RemoveField(
            model_name="declaracaoresidencia",
            name="idade",
        ),
        migrations.RemoveField(
            model_name="declaracaoviagem",
            name="idade",
        ),
        migrations.AddField(
            model_name="declaracaocoabitacao",
            name="data_nasc",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="declaracaocredencialviagem",
            name="data_nasc",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="declaracaomatricial",
            name="data_nasc",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="declaracaoobito",
            name="data_nasc",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="declaracaopobreza",
            name="data_nasc",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="declaracaoresidencia",
            name="data_nasc",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="declaracaoviagem",
            name="data_nasc",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
