# Generated by Django 4.1.3 on 2023-07-20 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("declaracao", "0004_remove_declaracaocoabitacao_idade_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="declaracaocoabitacao",
            name="bi",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="declaracaocredencialviagem",
            name="bi",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="declaracaomatricial",
            name="bi",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="declaracaoobito",
            name="bi",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="declaracaopobreza",
            name="bi",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="declaracaoresidencia",
            name="bi",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="declaracaoviagem",
            name="bi",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
