# Generated by Django 4.1.3 on 2023-07-20 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("declaracao", "0005_declaracaocoabitacao_bi_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="declaracaocoabitacao",
            name="status",
            field=models.CharField(default="Aguardando Aprovacao", max_length=100),
        ),
        migrations.AddField(
            model_name="declaracaocredencialviagem",
            name="status",
            field=models.CharField(default="Aguardando Aprovacao", max_length=100),
        ),
        migrations.AddField(
            model_name="declaracaomatricial",
            name="status",
            field=models.CharField(default="Aguardando Aprovacao", max_length=100),
        ),
        migrations.AddField(
            model_name="declaracaoobito",
            name="status",
            field=models.CharField(default="Aguardando Aprovacao", max_length=100),
        ),
        migrations.AddField(
            model_name="declaracaopobreza",
            name="status",
            field=models.CharField(default="Aguardando Aprovacao", max_length=100),
        ),
        migrations.AddField(
            model_name="declaracaoresidencia",
            name="status",
            field=models.CharField(default="Aguardando Aprovacao", max_length=100),
        ),
        migrations.AddField(
            model_name="declaracaoviagem",
            name="status",
            field=models.CharField(default="Aguardando Aprovacao", max_length=100),
        ),
    ]
