# Generated by Django 4.1.3 on 2023-07-20 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("declaracao", "0006_declaracaocoabitacao_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="declaracaocoabitacao",
            name="data_aprovacao",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="declaracaocoabitacao",
            name="data_registo",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="declaracaocredencialviagem",
            name="data_aprovacao",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="declaracaocredencialviagem",
            name="data_registo",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="declaracaomatricial",
            name="data_aprovacao",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="declaracaomatricial",
            name="data_registo",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="declaracaoobito",
            name="data_aprovacao",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="declaracaoobito",
            name="data_registo",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="declaracaopobreza",
            name="data_aprovacao",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="declaracaopobreza",
            name="data_registo",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="declaracaoresidencia",
            name="data_aprovacao",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="declaracaoresidencia",
            name="data_registo",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="declaracaoviagem",
            name="data_aprovacao",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="declaracaoviagem",
            name="data_registo",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
