# Generated by Django 4.1.3 on 2023-07-27 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("declaracao", "0008_declaracaocoabitacao_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="declaracaocoabitacao",
            name="bairro",
            field=models.CharField(default="Nhocane", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="declaracaocoabitacao",
            name="estado_civil",
            field=models.CharField(default="Solteiro", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="declaracaocredencialviagem",
            name="bairro",
            field=models.CharField(default="Nhocane", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="declaracaocredencialviagem",
            name="estado_civil",
            field=models.CharField(default="Solteiro", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="declaracaomatricial",
            name="bairro",
            field=models.CharField(default="Nhocane", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="declaracaomatricial",
            name="estado_civil",
            field=models.CharField(default="Solteiro", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="declaracaoobito",
            name="bairro",
            field=models.CharField(default="Nhocane", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="declaracaoobito",
            name="estado_civil",
            field=models.CharField(default="Solteiro", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="declaracaopobreza",
            name="bairro",
            field=models.CharField(default="Nhocane", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="declaracaopobreza",
            name="estado_civil",
            field=models.CharField(default="Solteiro", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="declaracaoresidencia",
            name="bairro",
            field=models.CharField(default="Nhocane", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="declaracaoresidencia",
            name="estado_civil",
            field=models.CharField(default="Solteiro", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="declaracaoviagem",
            name="bairro",
            field=models.CharField(default="Nhocane", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="declaracaoviagem",
            name="estado_civil",
            field=models.CharField(default="Solteiro", max_length=100, null=True),
        ),
    ]
