# Generated by Django 4.2.4 on 2023-09-18 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('declaracao', '0010_declaracaocoabitacao_pedido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='declaracaocoabitacao',
            name='bi_emissao',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='declaracaocoabitacao',
            name='bi_local',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='declaracaocoabitacao',
            name='conjo',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='declaracaocoabitacao',
            name='mae',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='declaracaocoabitacao',
            name='naturalidade',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='declaracaocoabitacao',
            name='nome',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='declaracaocoabitacao',
            name='pai',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='declaracaocoabitacao',
            name='status',
            field=models.CharField(default='Aguardando Aprovacao', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='declaracaocoabitacao',
            name='tempo_residencia',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='declaracaocredencialviagem',
            name='bi_emissao',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='declaracaocredencialviagem',
            name='bi_local',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='declaracaocredencialviagem',
            name='lotacao',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='declaracaocredencialviagem',
            name='mae',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='declaracaocredencialviagem',
            name='naturalidade',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='declaracaocredencialviagem',
            name='nome',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='declaracaocredencialviagem',
            name='pai',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='declaracaocredencialviagem',
            name='status',
            field=models.CharField(default='Aguardando Aprovacao', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='declaracaocredencialviagem',
            name='validade',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='declaracaocredencialviagem',
            name='veiculo_marca',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='declaracaocredencialviagem',
            name='veiculo_matricula',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='declaracaomatricial',
            name='bi_emissao',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='declaracaomatricial',
            name='bi_local',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='declaracaomatricial',
            name='mae',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='declaracaomatricial',
            name='naturalidade',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='declaracaomatricial',
            name='nome',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='declaracaomatricial',
            name='pai',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='declaracaomatricial',
            name='status',
            field=models.CharField(default='Aguardando Aprovacao', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='declaracaoobito',
            name='bi_emissao',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='declaracaoobito',
            name='bi_local',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='declaracaoobito',
            name='data_obito',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='declaracaoobito',
            name='mae',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='declaracaoobito',
            name='naturalidade',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='declaracaoobito',
            name='nome',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='declaracaoobito',
            name='pai',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='declaracaoobito',
            name='razao_obito',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='declaracaoobito',
            name='status',
            field=models.CharField(default='Aguardando Aprovacao', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='declaracaopobreza',
            name='bi_emissao',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='declaracaopobreza',
            name='bi_local',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='declaracaopobreza',
            name='mae',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='declaracaopobreza',
            name='naturalidade',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='declaracaopobreza',
            name='nome',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='declaracaopobreza',
            name='pai',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='declaracaopobreza',
            name='razao',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='declaracaopobreza',
            name='status',
            field=models.CharField(default='Aguardando Aprovacao', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='declaracaopobreza',
            name='tempo_residencia',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='declaracaoresidencia',
            name='bi_emissao',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='declaracaoresidencia',
            name='bi_local',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='declaracaoresidencia',
            name='mae',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='declaracaoresidencia',
            name='naturalidade',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='declaracaoresidencia',
            name='nome',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='declaracaoresidencia',
            name='pai',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='declaracaoresidencia',
            name='razao',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='declaracaoresidencia',
            name='status',
            field=models.CharField(default='Aguardando Aprovacao', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='declaracaoresidencia',
            name='tempo_residencia',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='declaracaoviagem',
            name='bi_emissao',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='declaracaoviagem',
            name='bi_local',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='declaracaoviagem',
            name='mae',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='declaracaoviagem',
            name='naturalidade',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='declaracaoviagem',
            name='nome',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='declaracaoviagem',
            name='nome_menor',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='declaracaoviagem',
            name='pai',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='declaracaoviagem',
            name='razao',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='declaracaoviagem',
            name='relacao_menor',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='declaracaoviagem',
            name='status',
            field=models.CharField(default='Aguardando Aprovacao', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='declaracaoviagem',
            name='tempo_residencia',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
