# Generated by Django 4.1.3 on 2023-07-15 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Municipe", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Propriedade",
            fields=[
                (
                    "id",
                    models.AutoField(
                        db_column="id_propriedade", primary_key=True, serialize=False
                    ),
                ),
                (
                    "quarteirao",
                    models.CharField(db_column="quarteirao", max_length=100),
                ),
                ("nr_casa", models.CharField(db_column="nr_casa", max_length=20)),
                ("bairro", models.CharField(db_column="bairro", max_length=100)),
                ("natureza", models.CharField(db_column="natureza", max_length=100)),
                ("tipo", models.CharField(db_column="tipo", max_length=100)),
                ("data_licenca", models.DateField(db_column="data_licenca")),
                (
                    "area_edificada",
                    models.DecimalField(
                        db_column="area_edificada", decimal_places=2, max_digits=10
                    ),
                ),
                (
                    "area_logradouro",
                    models.DecimalField(
                        db_column="area_logradouro", decimal_places=2, max_digits=10
                    ),
                ),
                (
                    "valor_patrimonial",
                    models.DecimalField(
                        db_column="valor_patrimonial", decimal_places=2, max_digits=10
                    ),
                ),
                (
                    "data_registro",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_column="data_registro",
                        verbose_name="Data de Registro",
                    ),
                ),
                (
                    "id_municipe",
                    models.ForeignKey(
                        db_column="id_Municipe",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Municipe.municipe",
                    ),
                ),
            ],
            options={
                "db_table": "propriedade",
            },
        ),
    ]
