# Generated by Django 4.1.3 on 2023-07-15 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Propriedade", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="propriedade",
            name="bairro",
            field=models.CharField(db_column="bairro", max_length=100, null=True),
        ),
    ]
