# Generated by Django 4.1.3 on 2023-07-18 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Taxa",
            fields=[
                (
                    "id",
                    models.AutoField(
                        db_column="id_taxa", primary_key=True, serialize=False
                    ),
                ),
                ("nome", models.CharField(db_column="nome_taxa", max_length=100)),
                ("rubrica", models.CharField(db_column="rubrica_taxa", max_length=100)),
                (
                    "valor",
                    models.DecimalField(
                        db_column="valor_taxa", decimal_places=2, max_digits=10
                    ),
                ),
                ("destino", models.CharField(db_column="destino_taxa", max_length=100)),
                ("lei", models.CharField(db_column="lei_taxa", max_length=100)),
                (
                    "periodicidade",
                    models.CharField(db_column="periodicidade_taxa", max_length=100),
                ),
                ("data_maxima", models.DateField(db_column="data_maxima_taxa")),
            ],
            options={
                "db_table": "taxa",
            },
        ),
    ]
