# Generated by Django 4.1.3 on 2023-07-25 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taxas", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taxa",
            name="nome",
            field=models.CharField(db_column="nome_taxa", max_length=250),
        ),
    ]
